### ISSUE TITLE
App unable to install

### ISSUE THREAD

**Issue by alizafardev** [Expensify/react-native-share-menu#26]
I have added a share extension into iOS project. Added the provide ObjectiveC code in extension.m file inside the loadview function.
Xcode gives me error (This app was unable to be installed)
how can I solve this ??

**Comment by ajith-ab** [comment]
use [react-native-file-share-intent](https://github.com/ajith-ab/react-native-file-share-intent)

**Comment by ajith-ab** [comment]
i ve used this package [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)

**Comment by infojunkie** [comment]
Hello @ajith-ab it looks that the package that you claim to be using is actually [your own creation](https://github.com/ajith-ab/react-native-receive-sharing-intent). Sounds like a disingenuous way to advertise for your module, by tagging every open issue here! It's also a pity you chose to create your own package from scratch, instead of contributing to an existing one.

**Comment by ajith-ab** [comment]
Hello @infojunkie I commented here due to this package cannot be updating by the Author and this package is only available for image and text. I have written package is Supports **file, image & text share receiving** . So here i will Commented here. I have created a package from scratch @infojunkie  please compare this two packages

**Comment by caiosba** [comment]
@Gustash can you please check if it's fixed now?

**Comment by Gustash** [comment]
This should be fixed now as the entire iOS module was rewritten. If this is still an issue post v3.0.0 feel free to re-open
