### ISSUE TITLE
Share audio?

### ISSUE THREAD

**Issue by giacomocerquone** [Expensify/react-native-share-menu#28]
Hi all, quick question, I saw the pr by @denvers and I'd like to ask you @caiosba : would that pr with few adjustments allow us to get the path of an audio file too?
And when will it be merged? 
Thank you very much :)

**Comment by caiosba** [comment]
The upload image PR was merged. For audio, I think it's just a matter of adding the relevant mime type.

**Comment by ajith-ab** [comment]
use [react-native-file-share-intent](https://github.com/ajith-ab/react-native-file-share-intent)

**Comment by ajith-ab** [comment]
i ve used this package [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)

**Comment by infojunkie** [comment]
Hello @ajith-ab it looks that the package that you claim to be using is actually [your own creation](https://github.com/ajith-ab/react-native-receive-sharing-intent). Sounds like a disingenuous way to advertise for your module, by tagging every open issue here! It's also a pity you chose to create your own package from scratch, instead of contributing to an existing one.

**Comment by ajith-ab** [comment]
Hello @infojunkie I commented here due to this package cannot be updating by the Author and this package is only available for image and text. I have written package is Supports **file, image & text share receiving** . So here i will Commented here. I have created a package from scratch @infojunkie  please compare this two packages
