### ISSUE TITLE
Share PDF?

### ISSUE THREAD

**Issue by MarkoDjordjevic85** [Expensify/react-native-share-menu#41]
Hey, can share possibility for PDF be implemented? Working on Android and adding a mimeType in AndroidManifest is not enough, there is a condition that has to be changed in ShareMenuModule.java.  Without it it says file type not supported.

Thank you

**Comment by ajith-ab** [comment]
i ve used this package with **all type of file support with multiple files also** [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)

**Comment by infojunkie** [comment]
Hello @ajith-ab it looks that the package that you claim to be using is actually [your own creation](https://github.com/ajith-ab/react-native-receive-sharing-intent). Sounds like a disingenuous way to advertise for your module, by tagging every open issue here! It's also a pity you chose to create your own package from scratch, instead of contributing to an existing one.

**Comment by ajith-ab** [comment]
Hello @infojunkie I commented here due to this package cannot be updating by the Author and this package is only available for image and text. I have written package is Supports **file, image & text share receiving** . So here i will Commented here. I have created a package from scratch @infojunkie  please compare this two packages
